// <auto-generated />
namespace MyChicken.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class V3_User_Order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V3_User_Order));
        
        string IMigrationMetadata.Id
        {
            get { return "201606090953168_V3_User_Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
