// <auto-generated />
namespace MyChicken.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class V4_Tel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V4_Tel));
        
        string IMigrationMetadata.Id
        {
            get { return "201606081315058_V4_Tel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
